let data = {
  code: 0,
  message: "success",
  contacts: [
    {
      contact_id: "808355000000229002",
      contact_name: "Abhay Verma",
      customer_name: "Abhay Verma",
      vendor_name: "Abhay Verma",
      company_name: "Tuf4",
      website: "",
      language_code: "",
      language_code_formatted: "",
      contact_type: "customer",
      contact_type_formatted: "Customer",
      status: "active",
      customer_sub_type: "business",
      source: "api",
      is_linked_with_zohocrm: false,
      payment_terms: 0,
      payment_terms_label: "Due On Receipt",
      currency_id: "808355000000000099",
      twitter: "",
      facebook: "",
      currency_code: "INR",
      outstanding_receivable_amount: 0.0,
      outstanding_receivable_amount_bcy: 0.0,
      outstanding_payable_amount: 0.0,
      outstanding_payable_amount_bcy: 0.0,
      unused_credits_receivable_amount: 0.0,
      unused_credits_payable_amount: 0.0,
      first_name: "",
      last_name: "",
      email: "",
      phone: "",
      mobile: "",
      portal_status: "disabled",
      created_time: "2020-08-16T11:28:04+0530",
      created_time_formatted: "16/08/2020",
      last_modified_time: "2020-08-16T11:28:04+0530",
      last_modified_time_formatted: "16/08/2020",
      custom_fields: [],
      custom_field_hash: {},
      ach_supported: false,
      gst_treatment: "business_gst",
      tax_treatment: "",
      gst_no: "",
      place_of_contact: "MH",
      place_of_contact_formatted: "Maharashtra",
      has_attachment: false,
    },
    {
      contact_id: "808355000000223021",
      contact_name: "Bowman and Co",
      customer_name: "Bowman and Co",
      vendor_name: "Bowman and Co",
      company_name: "Bowman and Co",
      website: "",
      language_code: "",
      language_code_formatted: "",
      contact_type: "customer",
      contact_type_formatted: "Customer",
      status: "active",
      customer_sub_type: "business",
      source: "api",
      is_linked_with_zohocrm: false,
      payment_terms: 0,
      payment_terms_label: "Due On Receipt",
      currency_id: "808355000000000099",
      twitter: "",
      facebook: "",
      currency_code: "INR",
      outstanding_receivable_amount: 0.0,
      outstanding_receivable_amount_bcy: 0.0,
      outstanding_payable_amount: 0.0,
      outstanding_payable_amount_bcy: 0.0,
      unused_credits_receivable_amount: 0.0,
      unused_credits_payable_amount: 0.0,
      first_name: "",
      last_name: "",
      email: "",
      phone: "",
      mobile: "",
      portal_status: "disabled",
      created_time: "2020-08-14T15:30:36+0530",
      created_time_formatted: "14/08/2020",
      last_modified_time: "2020-08-14T15:30:36+0530",
      last_modified_time_formatted: "14/08/2020",
      custom_fields: [],
      custom_field_hash: {},
      ach_supported: false,
      gst_treatment: "business_gst",
      tax_treatment: "",
      gst_no: "",
      place_of_contact: "MH",
      place_of_contact_formatted: "Maharashtra",
      has_attachment: false,
    },
    {
      contact_id: "808355000000229014",
      contact_name: "Gautam Gambhir",
      customer_name: "Gautam Gambhir",
      vendor_name: "Gautam Gambhir",
      company_name: "ICC",
      website: "",
      language_code: "",
      language_code_formatted: "",
      contact_type: "customer",
      contact_type_formatted: "Customer",
      status: "active",
      customer_sub_type: "business",
      source: "api",
      is_linked_with_zohocrm: false,
      payment_terms: 0,
      payment_terms_label: "Due On Receipt",
      currency_id: "808355000000000099",
      twitter: "",
      facebook: "",
      currency_code: "INR",
      outstanding_receivable_amount: 0.0,
      outstanding_receivable_amount_bcy: 0.0,
      outstanding_payable_amount: 0.0,
      outstanding_payable_amount_bcy: 0.0,
      unused_credits_receivable_amount: 0.0,
      unused_credits_payable_amount: 0.0,
      first_name: "",
      last_name: "",
      email: "",
      phone: "",
      mobile: "",
      portal_status: "disabled",
      created_time: "2020-08-16T11:28:27+0530",
      created_time_formatted: "16/08/2020",
      last_modified_time: "2020-08-16T11:28:27+0530",
      last_modified_time_formatted: "16/08/2020",
      custom_fields: [],
      custom_field_hash: {},
      ach_supported: false,
      gst_treatment: "business_gst",
      tax_treatment: "",
      gst_no: "",
      place_of_contact: "MH",
      place_of_contact_formatted: "Maharashtra",
      has_attachment: false,
    },
    {
      contact_id: "808355000000063013",
      contact_name: "Mr. Buyer A",
      customer_name: "Mr. Buyer A",
      vendor_name: "Mr. Buyer A",
      company_name: "BuyerOrg",
      website: "",
      language_code: "en",
      language_code_formatted: "English",
      contact_type: "customer",
      contact_type_formatted: "Customer",
      status: "active",
      customer_sub_type: "business",
      source: "user",
      is_linked_with_zohocrm: false,
      payment_terms: 0,
      payment_terms_label: "Due on Receipt",
      currency_id: "808355000000000099",
      twitter: "",
      facebook: "",
      currency_code: "INR",
      outstanding_receivable_amount: 0.0,
      outstanding_receivable_amount_bcy: 0.0,
      outstanding_payable_amount: 0.0,
      outstanding_payable_amount_bcy: 0.0,
      unused_credits_receivable_amount: 0.0,
      unused_credits_payable_amount: 0.0,
      first_name: "Buyer",
      last_name: "A",
      email: "siddharthlatest@gmail.com",
      phone: "",
      mobile: "",
      portal_status: "enabled",
      created_time: "2017-07-04T22:37:58+0530",
      created_time_formatted: "04/07/2017",
      last_modified_time: "2017-07-09T15:08:47+0530",
      last_modified_time_formatted: "09/07/2017",
      custom_fields: [
        {
          customfield_id: "808355000000063057",
          show_in_store: false,
          show_in_portal: false,
          is_active: true,
          index: 1,
          label: "GST Number",
          show_on_pdf: true,
          edit_on_portal: false,
          edit_on_store: false,
          show_in_all_pdf: true,
          value_formatted: "1234352143ABC",
          data_type: "string",
          placeholder: "cf_gst_number",
          value: "1234352143ABC",
        },
        {
          customfield_id: "808355000000063061",
          show_in_store: false,
          show_in_portal: false,
          is_active: true,
          index: 2,
          label: "Website",
          show_on_pdf: true,
          edit_on_portal: false,
          edit_on_store: false,
          show_in_all_pdf: true,
          value_formatted: "http://example.com",
          data_type: "url",
          placeholder: "cf_website",
          value: "http://example.com",
        },
      ],
      cf_gst_number: "1234352143ABC",
      cf_gst_number_unformatted: "1234352143ABC",
      cf_website: "http://example.com",
      cf_website_unformatted: "http://example.com",
      custom_field_hash: {
        cf_gst_number: "1234352143ABC",
        cf_gst_number_unformatted: "1234352143ABC",
        cf_website: "http://example.com",
        cf_website_unformatted: "http://example.com",
      },
      ach_supported: false,
      gst_treatment: "",
      tax_treatment: "",
      gst_no: "",
      place_of_contact: "",
      place_of_contact_formatted: "",
      has_attachment: false,
    },
    {
      contact_id: "808355000000063029",
      contact_name: "Mr. Seller B",
      customer_name: "Mr. Seller B",
      vendor_name: "Mr. Seller B",
      company_name: "SellerOrg",
      website: "",
      language_code: "",
      language_code_formatted: "",
      contact_type: "vendor",
      contact_type_formatted: "Vendors",
      status: "active",
      customer_sub_type: "business",
      source: "user",
      is_linked_with_zohocrm: false,
      payment_terms: 0,
      payment_terms_label: "Due on Receipt",
      currency_id: "808355000000000099",
      twitter: "",
      facebook: "",
      currency_code: "INR",
      outstanding_receivable_amount: 0.0,
      outstanding_receivable_amount_bcy: 0.0,
      outstanding_payable_amount: 1100.0,
      outstanding_payable_amount_bcy: 1100.0,
      unused_credits_receivable_amount: 0.0,
      unused_credits_payable_amount: 0.0,
      first_name: "Seller",
      last_name: "B",
      email: "siddharthlatest@gmail.com",
      phone: "",
      mobile: "",
      portal_status: "disabled",
      created_time: "2017-07-04T22:40:41+0530",
      created_time_formatted: "04/07/2017",
      last_modified_time: "2017-07-04T23:11:40+0530",
      last_modified_time_formatted: "04/07/2017",
      custom_fields: [],
      custom_field_hash: {},
      ach_supported: false,
      gst_treatment: "",
      tax_treatment: "",
      gst_no: "",
      place_of_contact: "",
      place_of_contact_formatted: "",
      has_attachment: false,
    },
    {
      contact_id: "808355000000066011",
      contact_name: "Sarat Chatterjee",
      customer_name: "Sarat Chatterjee",
      vendor_name: "Sarat Chatterjee",
      company_name: "Sarat chatterjee",
      website: "",
      language_code: "en",
      language_code_formatted: "English",
      contact_type: "customer",
      contact_type_formatted: "Customer",
      status: "active",
      customer_sub_type: "business",
      source: "user",
      is_linked_with_zohocrm: false,
      payment_terms: 0,
      payment_terms_label: "Due on Receipt",
      currency_id: "808355000000000099",
      twitter: "",
      facebook: "",
      currency_code: "INR",
      outstanding_receivable_amount: 0.0,
      outstanding_receivable_amount_bcy: 0.0,
      outstanding_payable_amount: 0.0,
      outstanding_payable_amount_bcy: 0.0,
      unused_credits_receivable_amount: 0.0,
      unused_credits_payable_amount: 0.0,
      first_name: "",
      last_name: "",
      email: "",
      phone: "",
      mobile: "9666760171",
      portal_status: "disabled",
      created_time: "2017-07-05T13:16:10+0530",
      created_time_formatted: "05/07/2017",
      last_modified_time: "2017-07-05T13:16:10+0530",
      last_modified_time_formatted: "05/07/2017",
      custom_fields: [],
      custom_field_hash: {},
      ach_supported: false,
      gst_treatment: "",
      tax_treatment: "",
      gst_no: "",
      place_of_contact: "",
      place_of_contact_formatted: "",
      has_attachment: false,
    },
    {
      contact_id: "808355000000074019",
      contact_name: "SHREE NM ELECTRICALS LIMITED",
      customer_name: "SHREE NM ELECTRICALS LIMITED",
      vendor_name: "SHREE NM ELECTRICALS LIMITED",
      company_name: "SHREE NM ELECTRICALS LIMITED",
      website: "",
      language_code: "",
      language_code_formatted: "",
      contact_type: "vendor",
      contact_type_formatted: "Vendors",
      status: "active",
      customer_sub_type: "business",
      source: "user",
      is_linked_with_zohocrm: false,
      payment_terms: 0,
      payment_terms_label: "Due on Receipt",
      currency_id: "808355000000000099",
      twitter: "",
      facebook: "",
      currency_code: "INR",
      outstanding_receivable_amount: 0.0,
      outstanding_receivable_amount_bcy: 0.0,
      outstanding_payable_amount: 33973.25,
      outstanding_payable_amount_bcy: 33973.25,
      unused_credits_receivable_amount: 0.0,
      unused_credits_payable_amount: 0.0,
      first_name: "",
      last_name: "",
      email: "mumbai@shreenm.com",
      phone: "22194748",
      mobile: "",
      portal_status: "disabled",
      created_time: "2017-07-10T17:34:56+0530",
      created_time_formatted: "10/07/2017",
      last_modified_time: "2017-07-10T17:43:43+0530",
      last_modified_time_formatted: "10/07/2017",
      custom_fields: [
        {
          customfield_id: "808355000000063057",
          show_in_store: false,
          show_in_portal: false,
          is_active: true,
          index: 1,
          label: "GST Number",
          show_on_pdf: true,
          edit_on_portal: false,
          edit_on_store: false,
          show_in_all_pdf: true,
          value_formatted: "27AADCS6037P1ZT",
          data_type: "string",
          placeholder: "cf_gst_number",
          value: "27AADCS6037P1ZT",
        },
      ],
      cf_gst_number: "27AADCS6037P1ZT",
      cf_gst_number_unformatted: "27AADCS6037P1ZT",
      custom_field_hash: {
        cf_gst_number: "27AADCS6037P1ZT",
        cf_gst_number_unformatted: "27AADCS6037P1ZT",
      },
      ach_supported: false,
      gst_treatment: "business_gst",
      tax_treatment: "",
      gst_no: "27AADCS6037P1ZT",
      place_of_contact: "MH",
      place_of_contact_formatted: "Maharashtra",
      has_attachment: false,
    },
    {
      contact_id: "808355000000073001",
      contact_name: "STULZ CHSPL (INDIA) PVT LTD)",
      customer_name: "STULZ CHSPL (INDIA) PVT LTD)",
      vendor_name: "STULZ CHSPL (INDIA) PVT LTD)",
      company_name: "STULZ CHSPL (INDIA) PVT LTD)",
      website: "",
      language_code: "en",
      language_code_formatted: "English",
      contact_type: "customer",
      contact_type_formatted: "Customer",
      status: "active",
      customer_sub_type: "business",
      source: "user",
      is_linked_with_zohocrm: false,
      payment_terms: 45,
      payment_terms_label: "Net 45",
      currency_id: "808355000000000099",
      twitter: "",
      facebook: "",
      currency_code: "INR",
      outstanding_receivable_amount: 0.0,
      outstanding_receivable_amount_bcy: 0.0,
      outstanding_payable_amount: 0.0,
      outstanding_payable_amount_bcy: 0.0,
      unused_credits_receivable_amount: 0.0,
      unused_credits_payable_amount: 0.0,
      first_name: "SANTOSH",
      last_name: "DHURI",
      email: "purchase1@stulzservice.in",
      phone: "022 2437 9173",
      mobile: "9821164416",
      portal_status: "disabled",
      created_time: "2017-07-10T16:05:15+0530",
      created_time_formatted: "10/07/2017",
      last_modified_time: "2017-07-10T17:18:37+0530",
      last_modified_time_formatted: "10/07/2017",
      custom_fields: [
        {
          customfield_id: "808355000000063057",
          show_in_store: false,
          show_in_portal: false,
          is_active: true,
          index: 1,
          label: "GST Number",
          show_on_pdf: true,
          edit_on_portal: false,
          edit_on_store: false,
          show_in_all_pdf: true,
          value_formatted: "27AABCC532OP1ZJ",
          data_type: "string",
          placeholder: "cf_gst_number",
          value: "27AABCC532OP1ZJ",
        },
      ],
      cf_gst_number: "27AABCC532OP1ZJ",
      cf_gst_number_unformatted: "27AABCC532OP1ZJ",
      custom_field_hash: {
        cf_gst_number: "27AABCC532OP1ZJ",
        cf_gst_number_unformatted: "27AABCC532OP1ZJ",
      },
      ach_supported: false,
      gst_treatment: "business_gst",
      tax_treatment: "",
      gst_no: "27AABCC5320P1ZJ",
      place_of_contact: "MH",
      place_of_contact_formatted: "Maharashtra",
      has_attachment: false,
    },
    {
      contact_id: "808355000000076001",
      contact_name: "Trinity Energy Systems Pvt. Ltd.",
      customer_name: "Trinity Energy Systems Pvt. Ltd.",
      vendor_name: "Trinity Energy Systems Pvt. Ltd.",
      company_name: "Trinity Energy Systems Pvt. Ltd.",
      website: "",
      language_code: "",
      language_code_formatted: "",
      contact_type: "vendor",
      contact_type_formatted: "Vendors",
      status: "active",
      customer_sub_type: "business",
      source: "user",
      is_linked_with_zohocrm: false,
      payment_terms: 0,
      payment_terms_label: "Due on Receipt",
      currency_id: "808355000000000099",
      twitter: "",
      facebook: "",
      currency_code: "INR",
      outstanding_receivable_amount: 0.0,
      outstanding_receivable_amount_bcy: 0.0,
      outstanding_payable_amount: 0.0,
      outstanding_payable_amount_bcy: 0.0,
      unused_credits_receivable_amount: 0.0,
      unused_credits_payable_amount: 0.0,
      first_name: "",
      last_name: "",
      email: "sales@trinityenergy.co.in",
      phone: "",
      mobile: "9228004452",
      portal_status: "disabled",
      created_time: "2017-07-13T10:46:33+0530",
      created_time_formatted: "13/07/2017",
      last_modified_time: "2017-07-13T10:46:33+0530",
      last_modified_time_formatted: "13/07/2017",
      custom_fields: [
        {
          customfield_id: "808355000000063057",
          show_in_store: false,
          show_in_portal: false,
          is_active: true,
          index: 1,
          label: "GST Number",
          show_on_pdf: true,
          edit_on_portal: false,
          edit_on_store: false,
          show_in_all_pdf: true,
          value_formatted: "24AACCT2043B1Z2",
          data_type: "string",
          placeholder: "cf_gst_number",
          value: "24AACCT2043B1Z2",
        },
      ],
      cf_gst_number: "24AACCT2043B1Z2",
      cf_gst_number_unformatted: "24AACCT2043B1Z2",
      custom_field_hash: {
        cf_gst_number: "24AACCT2043B1Z2",
        cf_gst_number_unformatted: "24AACCT2043B1Z2",
      },
      ach_supported: false,
      gst_treatment: "business_gst",
      tax_treatment: "",
      gst_no: "24AACCT2043B1Z2",
      place_of_contact: "GJ",
      place_of_contact_formatted: "Gujarat",
      has_attachment: false,
    },
  ],
  page_context: {
    page: 1,
    per_page: 10,
    has_more_page: false,
    report_name: "Contacts",
    applied_filter: "Status.All",
    custom_fields: [],
    sort_column: "contact_name",
    sort_order: "A",
  },
};

export function getContacts(status, page, pageSize) {
  //   let pageSize = 5;
  let filteredData = data.contacts.filter((element) => {
    if (status === "All") {
      return element;
    } else if (status === "Active") {
      if (element.status === "active") return element;
    }
  });
  let returnData = {
    contacts: filteredData.slice((page - 1) * pageSize, page * pageSize),
    has_more_page: filteredData.length - page * pageSize > 1,
  };

  console.log("returnData:", returnData);
  return returnData;
}
